In [1]:
import torch
import numpy as np
from trustworthai.utils.data_preprep.dataset_pipelines import load_data
from trustworthai.utils.data_preprep.splits import cross_validate_split

running on local machine!


In [2]:
trainds, _, _ = load_data(dataset="chal", test_proportion=0.15, validation_proportion=0.15, seed=3407, empty_proportion_retained=0.1, batch_size=32, dataloader2d_only=False, dataset3d_only=True)

In [3]:
len(trainds)

42

In [7]:
train, val = cross_validate_split(trainds, val_prop = 0.1, seed=3407, split=8)

In [8]:
train.new_indexes

array([ 0, 15, 30, 31, 26, 14,  6, 40, 12, 32,  4,  7, 41,  8, 38, 28, 29,
        2, 37, 22, 20, 35, 13, 23, 27, 19, 21, 39,  5, 16, 34,  9, 33,  3,
       11, 24,  1, 10])

In [9]:
val.new_indexes

array([17, 36, 18, 25])

In [2]:
import numpy as np

In [20]:
b = np.arange(0, 100, 1)
split = 5

size = len(b)
val_prop = 0.15
val_size = int(val_prop*size)
split_size = val_size

#assert split <= (size // split_size) - 1
assert split <= int(1/val_prop) - 1

if split == 0:
    b_train = b[split_size:]
    b_val = b[:split_size]
    
elif split == (len(b) // split_size) - 1:
#elif split == int(1/val_prop) - 1:
    b_train = b[:split_size * split]
    b_val = b[split_size * split:]
    
else:
    b_train = np.concatenate([b[0:split_size * split], b[split_size * (split + 1): ]])
    b_val = b[split_size * split : split_size * (split+1)]

#b_train = np.concatenate([b[0:split_size * s - 1], b[split_size * s + 1: ]])

In [21]:
b_val

array([75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
       92, 93, 94, 95, 96, 97, 98, 99])

In [64]:
b_val

array([36, 37, 38, 39, 40, 41])

In [59]:
int(np.ceil(101/ 10))

11

In [23]:
int(1//0.15) - 1

5